-- local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- local Network = require(ReplicatedStorage.Modules.Network)
--TODO: do this
--TODO: replace all ui (cuz it's from forsaken and i don't want stolen stuff >:( )

local ModPanel = {}

function ModPanel:Init()
    -- local HasRank, _Rank = Network:FireServerConnection("HasPermRank", "REMOTE_FUNCTION", "ServerOwner")
    -- if not HasRank then
    --     return
    -- end
end

function ModPanel:Start()
    
end

return ModPanel
